version: 0.0
os: linux
files:
  - source: /target/aws-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/my-application
    hooks:
      BeforeInstall:
        - location: scripts/install_dependencies.sh
          timeout: 300
          runas: root
      ApplicationStart:
        - location: scripts/start_server.sh
          timeout: 300
          runas: root