version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Or any other version you need, like corretto11
    commands:
      - echo Installing dependencies...
      - mvn clean install
  pre_build:
    commands:
      - echo Pre-build phase # Compile the code
      - mvn compile
      - echo "Creating ZIP file"
      - zip -r ImageGallery.zip target/*
  build:
    commands:
      - echo Build phase
      - mvn package  # Build the project and package it into a JAR/WAR
  post_build:
    commands:
      - echo Post-build phase
      - mvn test  # Run tests
      - mv target/aws-0.0.1-SNAPSHOT.zip .
      - ls -l target  # Проверка существования файла
      - echo "Uploading ZIP file to S3"
      - aws s3 cp aws-0.0.1-SNAPSHOT.zip s3://codepipeline-eu-north-1-205292741497/aws-0.0.1-SNAPSHOT.zip


artifacts:
  files:
    - target/*.jar  # Adjust as needed for your build output
    - aws-0.0.1-SNAPSHOT.zip

cache:
  paths:
    - ~/.m2/**/*  # Cache Maven dependencies
