version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Or any other version you need, like corretto11
    commands:
      - echo Installing dependencies...
      - mvn clean install
  pre_build:
    commands:
      - echo Pre-build phase # Compile the code
      - mvn compile
  build:
    commands:
      - echo Build phase
      - echo "Creating ZIP file from JAR"
      - zip -r target/aws-0.0.1-SNAPSHOT.zip target/aws-0.0.1-SNAPSHOT.jar  # Создание ZIP архива из JAR файла
      - ls -l target  # Проверка существования ZIP файла
  post_build:
    commands:
      - echo Post-build phase
      - echo "Uploading ZIP file to S3"
      - aws s3 cp target/aws-0.0.1-SNAPSHOT.zip s3://codepipeline-eu-north-1-205292741497/aws-0.0.1-SNAPSHOT.zip


artifacts:
  files:
    - target/*.jar  # Adjust as needed for your build output
    - aws-0.0.1-SNAPSHOT.zip

cache:
  paths:
    - ~/.m2/**/*  # Cache Maven dependencies
